## Numpy 리뷰


### 행렬, 벡터의 생성과 참조

#### numpy의 설치
- 가상환경의 선택 (가상환경의 이름이 *tf2*입니다)

    ```conda activate tf2```

- 선택한 가상환경에 numpy 패키지 설치
    
    ```conda install numpy```
- Anaconda 설치 경로의 확인

    ```%userprofile\anaconda3\envs```

#### 벡터와 행렬의 생성
- numpy.array 
    + 리스트를 이용한 벡터의 생성
    + numpy.zeros(), numpy.ones()
    + numpy.repeat()
    + 리스트를 이용한 행렬의 생성
- 대각행렬 생성하기 
    + numpy.diag()

#### 벡터와 행렬의 형태 변환
- shape 이해하기
- reshape 이해하기 (order = ‘C’ or ‘F’)

In [7]:
import numpy as np

In [11]:
# 리스트를 이용한 생성
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [10]:
# 속성확인
a.shape

(4,)

In [13]:
# 튜플을 이용한 생성
a = np.array((1,2,3,4))
print(a)

[1 2 3 4]


In [16]:
# range()를 이용한 생성
a = np.array(range(10))
print(a)

[0 1 2 3 4 5 6 7 8 9]


numpy.ndarray

In [18]:
# ones, zeros 함수를 이용한 생성
np.ones(5, dtype = 'float32')

array([1., 1., 1., 1., 1.], dtype=float32)

In [29]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
a = np.array(range(12)).reshape((2,6))
print("a의 shape는", a.shape, "입니다")
np.ones_like(a)

a의 shape는 (2, 6) 입니다


array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [40]:
# zeros
a = np.zeros((2,5), dtype = 'float16')
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float16)

In [41]:
np.zeros_like(a)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float16)

위 예제에서 a의 dtype이 'float16'이기 때문에 zeros_like 함수의 출력 array의 dtype이 'float16'이 된다.

In [43]:
# repeat pattern: each 3
np.repeat(1.5,3)

array([1.5, 1.5, 1.5])

In [44]:
# repeat pattern: each 4
np.repeat([1.5,3.5], 4)


array([1.5, 1.5, 1.5, 1.5, 3.5, 3.5, 3.5, 3.5])

In [46]:
# repeat pattern: each 2 and 3
np.repeat([1.5,3.5], [2,3])

array([1.5, 1.5, 3.5, 3.5, 3.5])

In [ ]:
np.repeat([[1,2,4]], 4, axis = 0)

array([[1, 2, 4],
       [1, 2, 4],
       [1, 2, 4],
       [1, 2, 4]])

tile 함수를 이용하면 위 예제와 같은 방법의 결과물을 얻을 수 있다.

In [59]:
np.tile([1,2,4], reps = (4,1))

array([[1, 2, 4],
       [1, 2, 4],
       [1, 2, 4],
       [1, 2, 4]])

In [68]:
# equally increasing
b = np.arange(-1, 3, 0.25)
b

array([-1.  , -0.75, -0.5 , -0.25,  0.  ,  0.25,  0.5 ,  0.75,  1.  ,
        1.25,  1.5 ,  1.75,  2.  ,  2.25,  2.5 ,  2.75])

In [69]:
b = np.arange(3, -1, -0.25)
b


array([ 3.  ,  2.75,  2.5 ,  2.25,  2.  ,  1.75,  1.5 ,  1.25,  1.  ,
        0.75,  0.5 ,  0.25,  0.  , -0.25, -0.5 , -0.75])

In [71]:
# render a diagonal matrix
b = np.diag([1,2,3,4])
b

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [73]:
# select diagonal elements
np.diagonal(b)

array([1, 2, 3, 4])

In [60]:
# shape 1
a = np.array([[1,2,3],[4,5,6]])
print(a)
a.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [61]:
# shape 2
a = np.array([[1,2,3]])
print(a)
a.shape

[[1 2 3]]


(1, 3)

In [62]:
# shape 3
a = np.array([[1],[2],[3]])
print(a)
a.shape

[[1]
 [2]
 [3]]


(3, 1)

k차원 numpy darray의 구조는 일렬로 배열된 1차원 array의 원소를 순서에 맞게 k차원으로 재배열한 것입니다.
아래 예제는 numpy darray에 재배열되는 순서를 확인할 수 있는 예제입니다. 2차원 배열에서 order = 'C' 방식과 order= 'F' 방식을 비교할 수 있습니다.

In [65]:
## shape + order 
a = np.array(range(12))
print("print a")
print(a)
print("order C")
print( a.reshape((4,3), order ="C"))
print("order F")
print( a.reshape((4,3), order ="F"))

print a
[ 0  1  2  3  4  5  6  7  8  9 10 11]
order C
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
order F
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### 행렬, 벡터의 원소 참조

#### 벡터의 원소 참조
- 슬라이싱 방법을 이용한 원소 참조
    + 단일 위치 참조
    + 연속 위치 참조1 [i:j]
    + 연속 위치 참조2 [i:j:k]
- boolean 벡터를 이용한 참조
    + 등호, 부등호를 이용한 boolean 벡터 만들기
    + boolean 벡터를 이용한 인덱싱
- 원소의 변경


#### 행렬의 원소 참조
- 슬라이싱 방법을 이용한 원소 참조
    + 단일 위치 참조 [i,j]
    + 연속 위치 참조1 (열 참조) [:,j], [:,j:k]
    + 연속 위치 참조2 (행 참조)
    + 연속 위치 참조3 (대각원소 참조) np.diagonal()
- boolean 행렬을 이용한 참조
    + 등호, 부등호를 이용한 boolean 행렬 만들기
    + boolean 행렬를 이용한 인덱싱
- 원소의 변경

In [76]:
# indexing
a = np.arange(3,20,2)
a

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [80]:
a[0]

3

In [79]:
a[:5]

array([ 3,  5,  7,  9, 11])

In [83]:

b = np.arange(50).reshape((5,10))
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [84]:
b[3,5]

35

In [87]:

b[3,:]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [89]:
b[:,3]

array([ 3, 13, 23, 33, 43])

In [90]:
# step i:j:k
b[:,3:9:2]

array([[ 3,  5,  7],
       [13, 15, 17],
       [23, 25, 27],
       [33, 35, 37],
       [43, 45, 47]])

slincing index를 활용하면 행의 순서를 바꿀수 있다. 아래 예제에서는 [4:0:-1] 혹은 [::-1]로 slicing 할 수 있다.

In [93]:
b[4:0:-1,:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

아래와 같이 대각원소를 참조할 수도 있다.

In [98]:
# 대각행렬 생성
b = np.diag([2,4,6,8])
# 대각원소 참조
np.diagonal(b)

array([2, 4, 6, 8])

In [108]:
np.random.seed(1)
b =np.random.uniform(size = 10)
b>0.25


array([ True,  True, False,  True, False, False, False,  True,  True,
        True])

In [109]:
b[b>0.25]

array([0.417022  , 0.72032449, 0.30233257, 0.34556073, 0.39676747,
       0.53881673])

In [112]:
b = np.random.normal(size = (5,5))
b<0

array([[False, False, False, False,  True],
       [False, False,  True, False,  True],
       [False, False, False,  True,  True],
       [ True, False, False, False,  True],
       [ True, False, False, False,  True]])

In [114]:
b[b<0] = 0
b

array([[0.83898341, 0.93110208, 0.28558733, 0.88514116, 0.        ],
       [1.25286816, 0.51292982, 0.        , 0.48851815, 0.        ],
       [1.13162939, 1.51981682, 2.18557541, 0.        , 0.        ],
       [0.        , 0.16003707, 0.87616892, 0.31563495, 0.        ],
       [0.        , 0.82797464, 0.23009474, 0.76201118, 0.        ]])

### 행렬의 덧셈과 곱셈
#### 행렬의 덧셈
- numpy.random.normal()을 이용한 랜덤행렬의 생성
- 열 벡터의 생성과 덧셈
- 행렬의 스칼라 곱

#### 행렬의 곱셈
- 행렬과 열벡터의 곱셈
- 회귀모형과 행렬의 곱셈 

#### 역행렬의 계산
- numpy.linalg.inv()를 이용한 역행렬의 계산
- 역행렬의 성질 확인

#### 고유치 분해(eigen decomposition)
- numpy.linalg.eig()를 이용한 고유치 분해
- 직교행렬의 확인

#### 특이치 분해(singular value decomposition)
- numpy.linalg.svd()를 이용한 특이치 분해

In [115]:
# operation
# addition on vectors
x = np.random.uniform(size = 10)
y = np.random.uniform(size = 10)

In [116]:
x + y

array([0.96090195, 0.94302923, 0.92602812, 1.29429412, 1.30669817,
       1.76505543, 0.83569807, 0.40345464, 0.60563941, 0.99580674])

In [117]:
3*x - 2*y

array([ 2.74117341,  1.59803235, -1.52205538,  1.18872703,  1.15598461,
        1.08501182,  1.88622765, -0.18555447, -1.11187814, -1.86055854])

In [118]:
x**2

array([8.69734298e-01, 4.85555550e-01, 4.35602280e-03, 5.70724424e-01,
       5.68329308e-01, 8.51974293e-01, 5.06267482e-01, 1.54432720e-02,
       3.95219721e-04, 6.87015833e-04])

In [119]:
# addition on matrix
x = np.random.uniform(size = (5,5))
y = np.random.uniform(size = (5,5))

In [120]:
x + y

array([[1.14238915, 0.98866728, 1.64746147, 0.47282203, 1.30087491],
       [1.00781636, 1.69252275, 0.90391304, 0.57481644, 0.20647737],
       [0.5462628 , 0.72767292, 0.61340332, 0.42485654, 1.21432549],
       [1.2927342 , 0.93985815, 0.5635042 , 0.81730871, 1.63650922],
       [0.83302002, 0.26962807, 0.62240994, 1.37354336, 0.40560349]])

In [121]:
3*x - 2*y

array([[ 0.5203728 , -1.88409811,  0.70824042,  0.2192273 ,  1.43377616],
       [-0.0763295 ,  0.93266376,  1.92778214,  1.6315683 ,  0.26932139],
       [-0.79293715, -0.84862856, -1.00404724, -0.31224243, -1.30010429],
       [ 0.9794765 ,  0.9188686 , -1.0642285 , -1.27474602,  1.5633632 ],
       [ 1.17446227,  0.47721004,  0.01680884,  0.97204255,  0.16594042]])

In [122]:
# matrix multiplication
x@y


array([[1.07598788, 1.18721825, 1.36051497, 1.07089097, 1.39539043],
       [1.48283019, 1.76559569, 1.24580821, 0.8466904 , 1.39153102],
       [0.25384287, 0.24156122, 0.23786419, 0.25301651, 0.20150382],
       [1.06558595, 1.25474581, 1.09630868, 0.84814677, 0.65512189],
       [1.06202305, 1.16831016, 1.13862922, 0.89757713, 1.08306606]])

In [123]:
# Transpose
A = np.array(range(0,6)).reshape((2,3))
A.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [124]:
# inverse matrix
A = np.array(range(4)).reshape((2,2))
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

Y 행렬 (정확히는 Y의 열벡터로 생성된 열공간)에 대한 projection matrix $\Pi_Y$는 
$$ \Pi_Y = Y(Y^\top Y)^{-1}Y^\top$$
로 주어진다.

In [126]:
#  orthogonal projection matrix onto Y
np.random.seed(1)
Y = np.random.gamma(1,1,(5,2)).round(2)
proj_Y = Y@np.linalg.inv(Y.T@Y)@Y.T
proj_Y

array([[ 0.68594235,  0.32203062, -0.04391301,  0.20065957,  0.26368372],
       [ 0.32203062,  0.47860442, -0.27190749,  0.02700205, -0.26678778],
       [-0.04391301, -0.27190749,  0.19567494,  0.03873089,  0.28288538],
       [ 0.20065957,  0.02700205,  0.03873089,  0.07249219,  0.15730104],
       [ 0.26368372, -0.26678778,  0.28288538,  0.15730104,  0.5672861 ]])

입력값 $x$에 대해 $\Pi_Yx$와  $x-\Pi_Yx$는 직교한다.

In [127]:
x = np.random.normal(0,1,5).round(2)
proj_Y@x

array([ 1.26955761, -0.28667715,  0.59618698,  0.55255645,  1.54100415])

In [128]:
x - proj_Y@x

array([ 0.47044239, -0.47332285, -0.27618698, -0.80255645, -0.08100415])

In [130]:
np.dot(proj_Y@x, (x - proj_Y@x))

3.219646771412954e-15

고유치 분해를 통해 정방행렬 A를 직교행렬 $E$와 대각행렬 $D$로 재표현할 수 있습니다.
$$A = EDE^\top$$

In [1]:
# eigendecomposition (page 51)
np.random.seed(1)
tmpA = np.random.gamma(1,1,(3,3)).round(2)
A = tmpA + tmpA.T
A

array([[1.08, 1.63, 0.21],
       [1.63, 0.32, 0.52],
       [0.21, 0.52, 1.02]])

In [2]:
eig_fit = np.linalg.eig(A)
# eigen matrix
E = eig_fit[1]
E

array([[ 0.59970893, -0.72900234, -0.33000726],
       [-0.78794538, -0.60990772, -0.08458518],
       [ 0.13961119, -0.31075418,  0.94018113]])

In [3]:
# diagonal element of D (saving memery)
d = eig_fit[0]
d

array([-1.01273625,  2.53322986,  0.89950639])

아래 코드로 $EDE^\top$를 계산함으로써 $A = EDE^\top$을 확인해 볼 수 있습니다.

In [4]:
# reconstruction 1
eig_fit[1]@np.diag(eig_fit[0])@eig_fit[1].T

array([[1.08, 1.63, 0.21],
       [1.63, 0.32, 0.52],
       [0.21, 0.52, 1.02]])

$E$ 행렬의 $j$번째 열벡터를 $e_j$ $D$행렬의 $j$번째 대각원소를 $\lambda_j$라고 하면 아래과 같이 $A$를 다시 쓸 수 있습니다.
$$A = \lambda_1 e_1e_1^\top + \lambda_2 e_2e_2^\top + \cdots + \lambda_p e_pe_p^\top $$

In [5]:
# reconstruction 2
E1 = E[:,[0]]@E[:,[0]].T
# note: eig_fit[1][:,0] 대신 eig_fit[1][:,[0]] 를 사용하면, dimension collapsing  을 방지해준다. 
E2 = E[:,[1]]@E[:,[1]].T
E3 = E[:,[2]]@E[:,[2]].T
d[0]*E1 + d[1]*E2 + d[2]*E3

array([[1.08, 1.63, 0.21],
       [1.63, 0.32, 0.52],
       [0.21, 0.52, 1.02]])

Singular Value Decompostion은 어떤 행렬을 직교행렬 두 개와 (부분)대각행렬 하나로 분해해준다. $n \times p$ 행렬 A를 생각해보자.
$$A=UDV^\top$$
- $U\in \mathbb{R}^{n \times n}$ 인 직교행렬
- $D\in \mathbb{R}^{n \times p}$ 인 부분대각행렬
- $V^\top \in \mathbb{R}^{p \times p}$ 인 직교행렬

In [10]:
np.random.seed(1)
A = np.random.gamma(1,1,(5,3)).round(2)
A


array([[0.54, 1.27, 0.  ],
       [0.36, 0.16, 0.1 ],
       [0.21, 0.42, 0.51],
       [0.77, 0.54, 1.16],
       [0.23, 2.1 , 0.03]])

In [27]:
u, d, vt = np.linalg.svd(A)

In [12]:
u

array([[-0.49856986, -0.13018396,  0.63725098, -0.09079361, -0.56581617],
       [-0.10260974,  0.14161256,  0.56562616, -0.30875843,  0.74441414],
       [-0.20737752,  0.28420105, -0.3645728 , -0.84769608, -0.15723344],
       [-0.36027421,  0.84296517, -0.056204  ,  0.39552836, -0.00326288],
       [-0.75372169, -0.41429157, -0.37135701,  0.14626489,  0.31775251]])

In [13]:
d

array([2.69648674, 1.34518023, 0.40453607])

In [22]:
D = np.concatenate([np.diag(d), np.zeros((2,3))], axis = 0)
D

array([[2.69648674, 0.        , 0.        ],
       [0.        , 1.34518023, 0.        ],
       [0.        , 0.        , 0.40453607],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ]])

In [31]:
vt

array([[-0.2968617 , -0.9323478 , -0.2063994 ],
       [ 0.4416951 , -0.32569784,  0.83595835],
       [ 0.84662776, -0.15699841, -0.50850067]])

In [32]:
u@D@vt

array([[ 5.40000000e-01,  1.27000000e+00, -1.34140343e-16],
       [ 3.60000000e-01,  1.60000000e-01,  1.00000000e-01],
       [ 2.10000000e-01,  4.20000000e-01,  5.10000000e-01],
       [ 7.70000000e-01,  5.40000000e-01,  1.16000000e+00],
       [ 2.30000000e-01,  2.10000000e+00,  3.00000000e-02]])

In [25]:
A

array([[0.54, 1.27, 0.  ],
       [0.36, 0.16, 0.1 ],
       [0.21, 0.42, 0.51],
       [0.77, 0.54, 1.16],
       [0.23, 2.1 , 0.03]])